services:
  benthos-opensearch-oauth2:
    image: jeffail/benthos:local
    build:
      context: ../../../
      dockerfile: ./resources/docker/Dockerfile
    command: [ '-w', '-c', '/benthos.yaml' ]
    volumes:
      - ./oauth2.yaml:/benthos.yaml
    network_mode: host

  benthos-opensearch-cachetest:
    image: jeffail/benthos:local
    build:
      context: ../../../
      dockerfile: ./resources/docker/Dockerfile
    command: [ 'test', '/benthos.yaml' ]
    volumes:
      - ./cache.yaml:/benthos.yaml
    network_mode: host
