# This is the default configuration file shipped with docker builds. It's
# extremely unlikely that a user would want to run Benthos without a custom
# configuration, so the purpose of this file is mostly to be a placeholder.
http:
  enabled: true

metrics:
  prometheus: {}

logger:
  format: json

input:
  label: "Input STDIN"
  type: stdin

processors:
  - processor1:
    label: "Processor 1"
    type: filter
    details:
      detail1: "Value1"
      detail2: "Value2"
    processors:
      - processor1:
        type: filter
        details:
          detail1: "Value1"
          detail2: "Value2"

  - processor2:
    label: "Processor 2"	
    type: modification
    details:
      detail1: "Value3"
      detail2: "Value4"
output:
  label: "Output STDOUT"
  type: stdout
