version: '3.3'
services:
  benthos-in:
    image: jeffail/benthos:local
    build:
      context: ../../../
      dockerfile: ./resources/docker/Dockerfile
    command: [ '-w', '-c', '/benthos.yaml' ]
    volumes:
      - ./in.yaml:/benthos.yaml
    network_mode: host

  benthos-out:
    image: jeffail/benthos:local
    build:
      context: ../../../
      dockerfile: ./resources/docker/Dockerfile
    command: [ '-w', '-c', '/benthos.yaml' ]
    volumes:
      - ./out.yaml:/benthos.yaml
    network_mode: host
  
  kafka-to-http:
    image: jeffail/benthos:local
    build:
      context: ../../../
      dockerfile: ./resources/docker/Dockerfile
    command: [ '-w', '-c', '/benthos.yaml' ]
    ports:
      - "4195:4195"
    volumes:
      - ./http.yaml:/benthos.yaml
    network_mode: host

  http-to-kafka:
    image: jeffail/benthos:local
    build:
      context: ../../../
      dockerfile: ./resources/docker/Dockerfile
    command: [ '-w', '-c', '/benthos.yaml' ]
    volumes:
      - ./stream_in.yaml:/benthos.yaml
    network_mode: host