# todo: read until <https://www.benthos.dev/docs/components/inputs/read_until> ?
http:
  address: 0.0.0.0:4195
  enabled: true
  root_path: /kafka
  debug_endpoints: false

logger:
  level: DEBUG
  format: logfmt
  add_timestamp: true
  static_fields:
    "@service": benthos

input:
  kafka_franz:
    seed_brokers: [localhost:9092] 
    topics: [JobNameInputTopic] 
    consumer_group: benthos2
    sasl:
      - mechanism: OAUTHBEARER 
        tokenEndpoint: http://localhost:1852/realms/local-development/protocol/openid-connect/token
        scope: "kafka" 
        clientId: "default-access" 
        clientSecret: "default-access-secret" 

pipeline:
  processors:
    - bloblang: |
        root = this
        meta "content-type" = "application/json"

    - catch:
        - log:
            level: ERROR
            message: ${! error() }
        - bloblang: root = deleted()

output:
  label: "http_out"
  http_server:
    address: "" # global
    timeout: 5s
    path: /get
    stream_path: /get/stream
    ws_path: /get/ws
    allowed_verbs:
      - GET