http:
  address: 0.0.0.0:4195
  enabled: true
  root_path: /benthos
  debug_endpoints: false

logger:
  level: DEBUG
  format: logfmt
  add_timestamp: true
  static_fields:
    "@service": benthos

input:
  label: source
  kafka_franz:
    seed_brokers: [localhost:9092] # No default (required)
    topics: [benthos_redpanda] # No default (required)
    consumer_group: benthos
    sasl:
      - mechanism: OAUTHBEARER # No default (required)
        tokenEndpoint: http://localhost:1852/realms/local-development/protocol/openid-connect/token
        scope: "kafka" # No default (required)
        clientId: "default-access" # No default (required)
        clientSecret: "default-access-secret" # No default (required)

pipeline:
  processors:
    - bloblang: |
        root = this

    - catch:
        - log:
            level: ERROR
            message: ${! error() }
        - bloblang: root = deleted()

output:
  stdout: {}
