name: Release cheetah-benthos

on:
  workflow_dispatch:

  push:
    branches: ["cheetah-main"]
    tags:
      - "v*"
  pull_request:
    branches: ["cheetah-main"]

env:
  IMAGE_NAME: ${{ github.repository }}
  DOCKERFILE_PATH: ./resources/docker/Dockerfile
  CONTEXT: ./

permissions:
  contents: read
  packages: write

jobs:
  push_image:
    name: "Build and push image"
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Build and push
        uses: trifork/cheetah-infrastructure-utils-workflows/.github/actions/build-image/default@main
        with:
          read_package_pat: ${{ secrets.PACKAGE_PAT }} # we need this, as GITHUB_TOKEN only have permission to its own repo
          context: ${{ env.CONTEXT }}
          image_name: ${{ env.IMAGE_NAME }}
          github_run_id: ${{ github.run_id }}
          dockerfile_path: ${{ env.DOCKERFILE_PATH }}
          push_image: ${{ (github.event_name == 'pull_request' || github.ref_type == 'tag' || github.event_name == 'workflow_dispatch') && 'true' || 'false' }}
          upload_image: "false"
